Repository pbg0205/airbnb, pull requests merged in 2021-05, with the labels that each got.

#4 Feature fe landing UI
  fe/.gitignore
  fe/README.md
  fe/config-overrides.js
  fe/package-lock.json
  fe/package.json
  fe/public/airbnb-logo.png
  fe/public/hero-img.png
  fe/public/index.html
  fe/src/App.tsx
  fe/src/assets/check.svg
  fe/src/assets/chevron-left.svg
  fe/src/assets/chevron-right.svg
  fe/src/assets/heart.svg
  fe/src/assets/menu.svg
  fe/src/assets/minus-circle.svg
  fe/src/assets/minus.svg
  fe/src/assets/pause-circle.svg
  fe/src/assets/plus-circle.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/assets/star.svg
  fe/src/assets/user.svg
  fe/src/assets/x-circle.svg
  fe/src/components/Header/Nav/Form.tsx
  fe/src/components/Header/Nav/Logo.tsx
  fe/src/components/Header/Nav/Menu.tsx
  fe/src/components/Header/Nav/Nav.tsx
  fe/src/components/Header/PageHeader.tsx
  fe/src/components/Header/Profile/Profile copy.tsx
  fe/src/components/Header/Profile/Profile.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/common/Title.tsx
  fe/src/index.tsx
  fe/src/pages/LandingPage.tsx
  fe/src/pages/SearchResult.tsx
  fe/src/react-app-env.d.ts
  fe/src/styles/reset.css
  fe/src/styles/theme.js
  fe/tsconfig.json
  fe/tsconfig.path.json
  fe/yarn.lock
Labels: FE

#5 Feature fe landing UI
  fe/config-overrides.js
  fe/package-lock.json
  fe/package.json
  fe/src/assets/search.svg
  fe/src/components/Header/Calender/Calendar.tsx
  fe/src/components/Header/Calender/CalendarWrap.tsx
  fe/src/components/Header/Calender/DayOfTheWeek.tsx
  fe/src/components/Header/Nav/Nav.tsx
  fe/src/components/Header/PageHeader.tsx
  fe/src/components/Header/ProfileMenu/Login.tsx
  fe/src/components/Header/ProfileMenu/Profile copy.tsx
  fe/src/components/Header/ProfileMenu/Profile.tsx
  fe/src/components/Header/Search/Date.tsx
  fe/src/components/Header/Search/Fare.tsx
  fe/src/components/Header/Search/Guests.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/Header/Search/SearchButton.tsx
  fe/src/components/common/Title.tsx
  fe/src/components/common/childType.ts
  fe/src/index.tsx
  fe/src/recoil/atoms/calendarState.ts
  fe/src/recoil/atoms/profileModal.ts
  fe/src/styles/reset.css
  fe/src/styles/theme.js
  fe/tsconfig.path.json
  fe/yarn.lock
Labels: FE, enhancement

#9 Feature be mockup
  BE/src/main/java/com/codsquad/airbnb/controller/AccomodationController.java
  BE/src/main/java/com/codsquad/airbnb/dto/AccomodationRequestDto.java
  BE/src/main/java/com/codsquad/airbnb/dto/AccomodationResponseDto.java
  BE/src/main/java/com/codsquad/airbnb/service/AccomodationService.java
  BE/src/main/resources/application.properties
Labels: BE

#13 캘린더 캐러셀 기능
  fe/package-lock.json
  fe/package.json
  fe/src/components/Header/Calender/Calendar.tsx
  fe/src/components/Header/Calender/CalendarWrap.tsx
  fe/src/components/Header/Calender/Day.tsx
  fe/src/components/Header/Calender/DayOfTheWeek.tsx
  fe/src/components/Header/ProfileMenu/Profile copy.tsx
  fe/src/components/Header/Search/Count.tsx
  fe/src/components/Header/Search/Date.tsx
  fe/src/components/Header/Search/GuestItem.tsx
  fe/src/components/Header/Search/GuestModal.tsx
  fe/src/components/Header/Search/Guests.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/common/Title.tsx
  fe/src/components/common/smallText.tsx
  fe/src/recoil/atoms/date.ts
  fe/src/recoil/atoms/guests.ts
  fe/yarn.lock
Labels: FE

#14 Chore: 캘린더 캐러셀 스타일 수정
  fe/src/components/Header/Calender/CalendarWrap.tsx
Labels: FE, enhancement

#17 날짜 선택 기능 추가. 스타일 적용.
  fe/src/components/Header/Calender/Calendar.tsx
  fe/src/components/Header/Calender/CalendarWrap.tsx
  fe/src/components/Header/Calender/Day.tsx
  fe/src/components/Header/Search/Date.tsx
  fe/src/components/Header/Search/Fare.tsx
  fe/src/components/Header/Search/GuestModal.tsx
  fe/src/components/Header/Search/Guests.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/common/smallText.tsx
  fe/src/recoil/atoms/date.ts
  fe/src/styles/reset.css
Labels: FE, enhancement

#19 Feat: 달력 날짜 선택에 따른 체크인 체크아웃 상태관리 완료
  fe/package-lock.json
  fe/package.json
  fe/src/components/Header/Calender/Calendar.tsx
  fe/src/components/Header/Calender/Day.tsx
  fe/src/components/Header/ProfileMenu/Login.tsx
  fe/src/components/Header/ProfileMenu/Profile.tsx
  fe/src/components/Header/ProfileMenu/queryString.d.ts
  fe/src/components/Header/Search/Date.tsx
  fe/src/recoil/atoms/date.ts
  fe/yarn.lock
Labels: FE, enhancement

#21 Refactor: 캘린더 리팩토링 했다.
  fe/src/components/Header/Calender/Day.tsx
  fe/src/recoil/atoms/date.ts
  fe/src/recoil/types/dateType.ts
Labels: FE, enhancement

#22 가격 차트 및 슬라이더 완료
  fe/public/pause-circle.svg
  fe/src/components/Header/Calender/CalendarWrap.tsx
  fe/src/components/Header/Nav/Menu.tsx
  fe/src/components/Header/PriceChart/ChartModal.tsx
  fe/src/components/Header/PriceChart/Graph.tsx
  fe/src/components/Header/PriceChart/testPrice.js
  fe/src/components/Header/Search/Count.tsx
  fe/src/components/Header/Search/Date.tsx
  fe/src/components/Header/Search/Fare.tsx
  fe/src/components/Header/Search/GuestItem.tsx
  fe/src/components/Header/Search/GuestModal.tsx
  fe/src/components/Header/Search/Guests.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/common/Loading.tsx
  fe/src/recoil/atoms/guests.ts
  fe/src/recoil/atoms/modalState.ts
  fe/src/recoil/atoms/price.ts
  fe/src/styles/theme.js
Labels: FE, enhancement

#27 Feat: 가격차트 마무리
  fe/src/App.tsx
  fe/src/components/Header/Nav/Nav.tsx
  fe/src/components/Header/PriceChart/ChartModal.tsx
  fe/src/components/Header/Search/Date.tsx
  fe/src/components/Header/Search/Fare.tsx
  fe/src/components/Header/Search/Guests.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/Header/Search/SearchButton.tsx
  fe/src/components/common/Loading.tsx
  fe/src/pages/SearchResult.tsx
  fe/src/recoil/atoms/page.ts
  fe/src/recoil/atoms/price.ts
Labels: FE, enhancement
